# Generated by Django 4.2.2 on 2023-07-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_alter_listing_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
